version: 0.2

phases:
  build:
    commands:
      - mvn -Pec2 -Pdocker -Ph2 -fn clean compile && mvn -DDOCKER_REGISTRY=452308943737.dkr.ecr.eu-central-1.amazonaws.com/swe/aws-demo -Pec2 -Pdocker -Ph2 generate-sources package

artifacts:
  files:
    - services/library-service/target/library-service-swarm.jar
    - services/frontend-service/target/frontend-service-swarm.jar
    - services/rental-service/target/rental-service-swarm.jar
    - services/users-service/target/users-service-swarm.jar
    