version: 0.2

phases:
  build:
    commands:
      - mvn -Pec2 -Pdocker -Ph2 -fn clean compile && mvn -Pec2 -Pdocker -Ph2 generate-sources package install

artifacts:
  files:
    - services/library-service/target/library-service-swarm.jar